In [2]:
import numpy as np
import torch

In [3]:
y = torch.tensor([[15,2,3,4], [1,2,20,10],[1,18,4,10],[13,12,5,3]])

batch_size = y.size(0)
sample_size = y.size(1)
print(batch_size)
# log_mean_exp
maximum_over_samples, _ = y.max(1)
print(maximum_over_samples)
stable_vec = y - maximum_over_samples.unsqueeze(1)
print(maximum_over_samples.unsqueeze(1))
stable_vec = stable_vec.type(torch.FloatTensor)
test = maximum_over_samples + (stable_vec.exp().mean(dim=1)).log()
print(test)

4
tensor([15, 20, 18, 13])
tensor([[15],
        [20],
        [18],
        [13]])
tensor([13.6137, 18.6138, 16.6140, 11.9272])


In [22]:
target = torch.tensor([[15,2,3,4], [1,2,20,10],[1,18,4,10],[13,12,5,3]])
mu = torch.tensor([[0.2,0.2,0.2,0.3],[0.2,0.2,0.2,0.3],[0.2,0.2,0.2,0.3],[0.2,0.2,0.2,0.3]])

In [30]:

batch_size = mu.size(0)
mu = mu.view(batch_size, -1)
print(mu.shape)
target = target.view(batch_size, -1)

    # log_likelihood_bernoulli
print((target*torch.log(mu) + (1-target)*torch.log(1-mu)).mean(dim=1))


torch.Size([4, 4])
tensor([ -8.0353, -10.3460, -10.3460, -11.2892])


tensor([-33.4942, -45.9709, -45.9709, -28.3175])


tensor([[-21.0176,  -2.9957,  -4.3820,  -5.7683],
        [ -1.6094,  -2.9957, -27.9490, -14.0861],
        [ -1.6094, -25.1764,  -5.7683, -14.0861],
        [-11.3715, -10.5242,  -4.5932,  -2.8986]])
